### ISSUE TITLE
Provide downlit format wrapper for html or md documents

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/downlit#124]
Currently, since downlit is intended to be used by other packages, it's difficult to apply downlit in situations where the user has less control over the output format (e.g. blogdown, learnr, etc.).

downlit could provide two functions, `downlit_html()` and `downlit_md()` that are rmarkdown output formats with a downlit post-processor.

For example, for a standard HTML document with custom options

```
---
output: 
  html_document:
    toc: true
    df_print: tibble
---
```

a user could ask for downlit to automatically post-process the output by using a `downlit::downlit_html` parent output format:

```
---
output:
  downlit::downlit_html:
    html_document:
      toc: true
      df_print: tibble
---
```

**Comment by cderv** [comment]
@gadenbuie original plan was to bring support into `html_document` directly https://github.com/rstudio/rmarkdown/issues/1881. 

There is a proposal https://github.com/rstudio/rmarkdown/pull/1941 which still await some review and probably updates with newer downlit. (We plan to work on rmarkdown this month). There was an issue with **bookdown** however regarding how the processing is done using **xml2**.  

For now, only **distill** has integrated support for highlighting using a knitr hook. 

Having a wrapper format is another interesting option - offering integration is usual format seems best however. What do you think ?

**Comment by cderv** [comment]
@gadenbuie Support has been added in `html_document()` in rstudio/rmarkdown#1941 using `highlight_downlit: TRUE` in YAML. 

For `github_document()` or `md_document`, this is a bit different as highlighting won't be useful. I have opened https://github.com/rstudio/rmarkdown/issues/2284 to track and discuss.
