### ISSUE TITLE
Consider adding line numbers

### ISSUE THREAD

**Issue by hadley** [r-lib/downlit#13]
Probably copying what goldmark does with a two column table. Both columns are wrapped in `<pre>`, left column is `seq_along(lines)`. 

See https://github.com/jemus42/hugodown-testing/blob/master/public/plain-markdown/index.html#L133 for specific classes

**Comment by hadley** [comment]
It's hard to see how to make this work for hugodown since knitr/evaluate breaks up the output into multiple pieces (so would have to carefully consider how to sequence line numbers across the outputs).

Maybe `highlight()` could add an attribute giving the number of lines, and also provide a helper method that would generate the table?

**Comment by maelle** [comment]
not sure if interesting but saw https://stackoverflow.com/a/57883514

**Comment by hadley** [comment]
Seems like we can just preserve pandoc's, rather than trying to roll our own.
