### ISSUE TITLE
More tolerant URL parsing?

### ISSUE THREAD

**Issue by maelle** [r-lib/downlit#14]
The `magick` package has this [URL field](https://github.com/ropensci/magick/blob/a144dd33f433c5e177c8c330c4427fede1d1334c/DESCRIPTION#L17
) (cc @jeroen)

```yaml
URL: https://docs.ropensci.org/magick (website) https://github.com/ropensci/magick (devel)
```

It's not parsed correctly by `package_urls()`. Would it make sense to use code/functions from `desc`?

``` r
desc::desc("/home/maelle/R/x86_64-pc-linux-gnu-library/3.6/magick/DESCRIPTION")$get_urls()
#> [1] "https://docs.ropensci.org/magick"   "https://github.com/ropensci/magick"
```

<sup>Created on 2020-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I am not sure how often `DESCRIPTION` URLs don't use "," as a separator.

**Comment by hadley** [comment]
I'm trying to keep this package as low dependency as possible, but I could probably copy the regexp that desc uses. Or @jeroen could use the standard url format 😄
