### ISSUE TITLE
flair and downlit

### ISSUE THREAD

**Issue by maelle** [r-lib/downlit#15]
Seeing #13 I thought about [Chroma line highlighting](https://ropensci.org/technotes/2020/04/30/code-highlighting/#emphasize-parts-of-your-code)

Which reminded me of [flair](https://education.rstudio.com/blog/2020/05/flair/) which makes me wonder, do downlit and flair work well together?

**Comment by hadley** [comment]
They're probably completely orthogonal. It would be interesting to think about if they could be made to work together, but I think that'd be hard because the colours would be fighting for dominance.

**Comment by maelle** [comment]
ah that's too bad!
