### ISSUE TITLE
`autolink_url()` doesn't handle `library`, `require` and `requireNamespace` properly

### ISSUE THREAD

**Issue by dmurdoch** [r-lib/downlit#151]
As mentioned here:  https://github.com/r-lib/pkgdown/issues/2155 , there are some issues in the `href_expr()` function called by `autolink_url()`.  The former assumes that all of `library`, `require` and `requireNamespace` accept a name as the first argument, and use it as a package name.  For example,

    autolink_url("library(MASS)")

returns `"http://www.stats.ox.ac.uk/pub/MASS4/"` correctly. This would also work with `require()`.  However, `autolink_url()` gives the same result from

    autolink_url("requireNamespace(MASS)")

even though `requireNamespace(MASS)` always treats `MASS` as a variable name, not a package name (so you'd usually get something like

    Error in requireNamespace(MASS) : object 'MASS' not found

Both `library()` and `require()` allow variables holding package names, but only with argument `character.only = TRUE`.  The `extract_package_attach()` function knows this, but `href_expr()` doesn't.

I'll try to put together a PR to handle these issues, but it'll be a few days, so someone else might want to do it first.

**Comment by hadley** [comment]
I'll try and take a stab at this tomorrow so I can push out a release that fixes the other major issue.
