### ISSUE TITLE
`downlit::href_package()` errors if the package is not installed

### ISSUE THREAD

**Issue by mikemahoney218** [r-lib/downlit#159]
``` r
try(remove.packages("mlbench"), silent = TRUE)
#> Removing package from '/home/mikemahoney218/R/x86_64-pc-linux-gnu-library/4.2'
#> (as 'lib' is unspecified)
downlit::href_package("mlbench")
#> Error in readRDS(con): error reading from connection

install.packages("mlbench")
#> Installing package into '/home/mikemahoney218/R/x86_64-pc-linux-gnu-library/4.2'
#> (as 'lib' is unspecified)
downlit::href_package("mlbench")
#> [1] NA
```

<sup>Created on 2022-09-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

It would be nice if this function returned NA if the URL can't be found (which is what's documented). 

The real-world place this came up is that this is causing pkgdown builds to fail in https://github.com/tidymodels/rsample/pull/365 , as (quoting Julia from https://github.com/r-lib/pkgdown/issues/2145) the rsample package has the [output of a reprex in its README](https://rsample.tidymodels.org/) because we don't want to include those packages as dependencies; they are not needed for anything except the demo in the README.

**Comment by hadley** [comment]
I can't reproduce this 😢 

``` r
rlang::is_installed("mlbench")
#> [1] FALSE
downlit::href_package("mlbench")
#> [1] NA
```

<sup>Created on 2022-09-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mikemahoney218** [comment]
...Huh, weird, I can't reproduce myself either anymore. Sorry; not sure what the root cause actually was, then.
