### ISSUE TITLE
Autolink fails when `?` topic contains hyphen

### ISSUE THREAD

**Issue by davidchall** [r-lib/downlit#168]
To generate a link to a topic containing a hyphen, we must use `help("topic")` instead of `?topic`.

``` r
withr::with_options(list(downlit.attached = "vctrs"), {
  print(downlit::autolink("help('faq-compatibility-types')"))
  print(downlit::autolink("?faq-compatibility-types"))
})
#> [1] "<a href='https://vctrs.r-lib.org/reference/faq-compatibility-types.html'>help('faq-compatibility-types')</a>"
#> [1] NA
```

<sup>Created on 2023-04-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dmurdoch** [comment]
In base R, `?faq-compatibility-types` would link to the help on the subtraction operator, which is probably not what was intended.  You would need to put the alias in quotes or backticks.  So what `downlit` does is probably reasonable.

**Comment by davidchall** [comment]
Ah, that's a fair point. Thanks, @dmurdoch!
