### ISSUE TITLE
Surprising bslib autolinking

### ISSUE THREAD

**Issue by maelle** [r-lib/downlit#175]
``` r
downlit::autolink("library(bslib)")
#> [1] "<a href='https://rstudio.github.io/bslib/'>library(bslib)</a>"
downlit::autolink("bslib::bs_bundle")
#> [1] "<a href='https://rdrr.io/pkg/bslib/man/bs_bundle.html'>bslib::bs_bundle</a>"
```

<sup>Created on 2023-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

this makes one of pkgdown snapshot test fail.

bslib has the pkgdown URL set up correctly in the pkgdown config file and in DESCRIPTION.

**Comment by maelle** [comment]
``` r
 downlit:::remote_urls("bslib")
#> NULL
```

<sup>Created on 2023-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
I suspect this is due to the very custom article layout:

https://github.com/rstudio/bslib/blob/f4a36e845bb78a326fcbe63994ae630fb2c5c35e/_pkgdown.yml#L38-L78

So may be it's a pkgdown bug after all?

**Comment by hadley** [comment]
Now in https://github.com/r-lib/pkgdown/issues/2350
