### ISSUE TITLE
Ability to pass something else than classes to highlight

### ISSUE THREAD

**Issue by maelle** [r-lib/downlit#25]
I'm trying to use downlit for Wordpress and was wondering whether it'd make sense to use colors as an argument instead of classes.

At the moment I'm using the same classes as the syntax highlighter plugin that Wordpress docs mention.  Limitations

* that highlighter doesn't seem adapted to add your own blocks and use its CSS (I didn't succeed in doing that https://rmd-wordpress.eu/rest-api-1/)

* that highlighter seems to have less granularity than downlit (e.g. ":" is "r plain").

**Comment by hadley** [comment]
I think this is probably part of #24.

But what do you mean about colours vs classes? You want donwlit to generate inline styles, directly setting the colours of the components?

**Comment by maelle** [comment]
yes, that is what I mean! And then it'd be great to be able to do that for the pre div as well.

In the case of Wordpress for instance, it'd make setup very easy (not asking users to add CSS nor a plugin).

I'm wondering whether it could work with Chroma classes + Chroma CSS (I'd give that as an argument and it'd give inline-styled html), but that's probably a bit more involved?

**Comment by hadley** [comment]
Yeah, I'd prefer to stick with classes for now. I can consider inline styles as part of #24.
