### ISSUE TITLE
More package linking in inline code

### ISSUE THREAD

**Issue by maelle** [r-lib/downlit#27]
Could

```markdown
Check out the `{downlit}` package!
```

become

```markdown
Check out the [downlit](url) package!
```
?

**Comment by hadley** [comment]
I'd be happy to accept a PR that did this — you'd need to add some logic https://github.com/r-lib/downlit/blob/master/R/downlit-md.R#L101-L106, checking to see if `x$c[[2]]` matches a regular expression, and if so, finding the link using `href_package()`.
