### ISSUE TITLE
Custom class for output comments

### ISSUE THREAD

**Issue by TimTeaFan** [r-lib/downlit#33]
Currently, output starting with `# ...` (especially the tidyverse output style `#> ...`) is treated as a regular comment. Readability-wise it would great to - at least have the chance to - assign a different class to output. Maybe this is just my personal preference and in this case please feel free to close this issue immediately.

For my own personal use I have installed a forked version of {downlit} which uses a (overly) simple implementation (ref. [here](https://github.com/TimTeaFan/downlit/blob/392deff6cd0946d93fdc2bec5c69469dea5c594b/R/highlight.R#L125) and [here](https://github.com/TimTeaFan/downlit/blob/392deff6cd0946d93fdc2bec5c69469dea5c594b/R/highlight.R#L173)). It assigns all "COMMENT" tokens which start with `#>` and have `parent == 0` the class `Generic.Output` (`go`).

It would take some thinking to generalize this so that users can specify their own output style. The implementation seems to be easy as long output starts with a leading pound `#`. Another option would be to only allow tidy style output `#> ` to have its own class.

**Comment by hadley** [comment]
Doing this fully (to support any knitr `comment` setting would be hard), but special casing `#>` seems reasonable to me.

**Comment by hadley** [comment]
Think about this more, I think this should happen elsewhere, i.e. during evaluation (as in the new `evaluate_and_highlight()` function)
