### ISSUE TITLE
should argument-less library(), vignette(), etc. be linked?

### ISSUE THREAD

**Issue by maelle** [r-lib/downlit#46]
Should `library()` become `[library()](https://rdrr.io/r/base/library.html)` instead of not being linked? Or was it a design decision?

I've just noticed this in a post where I mention `library()` and `require()` and was a bit surprised they weren't linked.

**Comment by hadley** [comment]
I think it's a buglet, because I designed it for the `library(ggplot2)` case (where it links to the package home). Do you want to do a PR? (https://github.com/krlmlr/downlit/blob/b-extra-newline/R/link.R#L78)

**Comment by maelle** [comment]
I'll try to get to it tomorrow or next week. Buglet is such a cute word :grin:

**Comment by hadley** [comment]
There's also bugatelle 😆
