### ISSUE TITLE
Turn on pillar.bold option when rendering examples and articles

### ISSUE THREAD

**Issue by krlmlr** [r-lib/downlit#49]
These should look good on the web. The default is `FALSE` in pillar because bold-face isn't supported too well in some terminals.

Not sure whose responsibility it should be -- we could also turn on in pillar if pkgdown is detected.

**Comment by krlmlr** [comment]
We also need to do this in Rmd formats that enable downlit.

**Comment by hadley** [comment]
Actually is that true? It still depends on using a code font with a correctly sized bold variant.

**Comment by hadley** [comment]
So I think this needs to remain in the hands of the user.
