### ISSUE TITLE
Auto-link system.file(..., package = pkg) calls to source file

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/downlit#65]
When visiting the [`codemetar::write_codemetar()` page](https://docs.ropensci.org/codemetar/reference/write_codemeta.html), I expected the following code:

```r
system.file("templates", "codemeta-github-actions.yml", package = "codemetar")
```

to lead me to source file but instead, it links to the unhelpful documentation of `system.file()`. I would expect/hope a link to https://github.com/ropensci/codemetar/blob/master/inst/templates/codemeta-github-actions.yml or https://raw.githubusercontent.com/ropensci/codemetar/master/inst/templates/codemeta-github-actions.yml.

I understand it may be difficult to link to the source file for arbitrary `system.file()` calls but calls relating to files from the package to which the pkgdown page relates to would be a good start. In the example here, since this is on the website for codemetar, it would work at least for `system.file(..., package = "codemetar")`.

Feel free to move this issue if you believe this should be pkgdown's job.

**Comment by hadley** [comment]
This feels like a lot of work for relatively little gain because not that many examples actually use `system.file()`. So it's unlikely that I would ever do it, but a PR would definitely be appreciated.

**Comment by hadley** [comment]
This is even more complicated than I thought because downlit currently has no notion of development repo, so I'm going to close to reflect the fact that it's unlikely that I'll ever work on it.
