### ISSUE TITLE
Produce Hugo compatible names

### ISSUE THREAD

**Issue by hadley** [r-lib/downlit#7]
https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css

**Comment by hadley** [comment]
By default, hugo inlines all the styles, so not much to do here. Just as easy to stick with the pandoc styles, and you can style with the rest of your site.

**Comment by maelle** [comment]
I am curious about this, sorry in advance for the noise. We use `usePygmentsClasses=true` (which means Chroma uses classes) in rOpenSci website for instance, and have a slightly tweaked stylesheet (tweaked compared to the one initially generated by Hugo). 

If downlit creates different class names for highlighting compared to Chroma (or inline styling), in a Hugo website with R code highlighted with downlit and other languages (even just YAML) highlighted with Chroma, would one need two stylesheets? 

Seeing your issue, I was hoping that for hugodown outputs downlit could let one choose between inline styling and styling with Chroma-named classes+stylesheet.

**Comment by hadley** [comment]
Oh if someone is already using the custom classes, I can do the extra work. Can you please point me to the css you have? (So I can easily see the class names)

**Comment by maelle** [comment]
Yay, thank you!

You can generate the stylesheet for any style with https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css

Ours at the moment https://github.com/ropensci/roweb2/blob/master/themes/ropensci/static/css/pygments.css

**Comment by maelle** [comment]
(A custom stylesheet is often needed to add contrast compared to default Chroma styles)

**Comment by maelle** [comment]
One thing I have not found is a table of equivalence between highlight.js/prism.js/Chroma/pandoc classes. Like a Rosetta stone, That might exist. 

Chroma styles were automatically created from Pygments styles so at least there's a translation Pygments/Chroma I know of.

**Comment by hadley** [comment]
Ok, I'm not going to produce something that detailed, but I'll do the basics and then you can customise further via PR if needed.

**Comment by maelle** [comment]
Yeah not everything is used for R code. Thanks!

**Comment by hadley** [comment]
I just realised this is really the right approach — we'll need to encourage people to set `usePygmentsClasses=true` so that the syntax highlighting from chroma and downlit matches.

**Comment by hadley** [comment]
And here's an example: https://deploy-preview-450--tidyverse-org.netlify.app/blog/2020/06/dplyr-1-0-0/

**Comment by maelle** [comment]
Separate issue: now at least one color pair from that style has too law contrast according to https://color.a11y.com/Contrast/ (that apparently wasn't able to evaluate color contrast for inline styling) -- our own pygments.css is really close but I darkened a few colors by hand.
