### ISSUE TITLE
Consider making autolink configurable to open links in a new tab

### ISSUE THREAD

**Issue by mattwarkentin** [r-lib/downlit#76]
Hi @hadley,

What are your thoughts about possibly adding an argument to `autolink()` in order to allow the package developer and/or user to decide whether the generated `<a>` tags open links in new tabs rather than in the current tab (i.e. `target="_blank"`)?

I believe the relevant code is...
https://github.com/r-lib/downlit/blob/47270f5bfe400ccf1db6b6c16e809cf538c0f021/R/link.R#L14-L21

Happy to contribute a PR, if you're interested.

**Comment by hadley** [comment]
I really dislike taking this out of the users control, so it would take a lot of convincing.

**Comment by mattwarkentin** [comment]
I barely had the conviction to submit this issue...haha.

I thought about it more after I posted this and I agree with you. I had an edge-case in mind, but it wouldn't take much JavaScript to achieve this anyway.
