### ISSUE TITLE
Peculiar styling of messages in example output

### ISSUE THREAD

**Issue by jennybc** [r-lib/downlit#79]
I can't figure out how downlit is deciding to show some messages in bold and not others.

I'm seeing this in the googlesheets4 examples. Here are few examples as of https://github.com/tidyverse/googlesheets4/commit/9309c2a49ed0eedfa66aabd5757b0c4e79cf99f9

Probably relevant: googlesheets4 is using cli (therefore `rlang::inform()`) for messages now.

The basic pattern is:  the first googlesheets4 message is bold, but no others.

Messages originating elsewhere, presumably coming via `message()` are ?always? bold. ("Files trashed..." is always coming from googledrive, for example).

Below is a sampler.

---

https://googlesheets4.tidyverse.org/reference/range_read.html#examples

https://github.com/tidyverse/googlesheets4/commit/9309c2a49ed0eedfa66aabd5757b0c4e79cf99f9#diff-c089033b92eaa2e50242f2188feedb0d449c5fd93c1765301867ee1c9bb1ae39

<img width="441" alt="Screen Shot 2021-03-08 at 4 14 09 PM" src="https://user-images.githubusercontent.com/599454/110398771-5bf92080-8029-11eb-8848-615928301ab0.png">

---

https://googlesheets4.tidyverse.org/reference/range_speedread.html#examples

https://github.com/tidyverse/googlesheets4/commit/9309c2a49ed0eedfa66aabd5757b0c4e79cf99f9#diff-c755ed40978311fdb955d656db19f8477496e343ec19095b0cfcf64716ca26ec

<img width="362" alt="Screen Shot 2021-03-08 at 4 16 25 PM" src="https://user-images.githubusercontent.com/599454/110398889-a7abca00-8029-11eb-98c5-132d93963b2e.png">

---

https://googlesheets4.tidyverse.org/reference/sheet_write.html

https://github.com/tidyverse/googlesheets4/commit/9309c2a49ed0eedfa66aabd5757b0c4e79cf99f9#diff-19e7740a2d283dc1311c374e0bb4b937e9a904f3dbef7acb84432b9053abff3f

<img width="359" alt="Screen Shot 2021-03-08 at 4 19 25 PM" src="https://user-images.githubusercontent.com/599454/110399113-15f08c80-802a-11eb-9b9c-c07e5e10c0b6.png">

**Comment by cderv** [comment]
Just sharing what I saw yesterday when the question was ask. 

**pkgdown** is setting a CSS for not of class message: https://github.com/r-lib/pkgdown/blob/dd94073575aaee2fd480892d24dfe0be85f81a03/inst/assets/pkgdown.css#L308
```css
.message { color: black;   font-weight: bolder;}
```

This seem to lead to the bold text. 

About not everything is bold : **downlit** does not seem to produce valid HTML in this case: the closing `</span>` for class message is not at the right place. 

See below, 
* With message we correctly get `</span></div>`
* Using `gs4_success`, we get `</div></span>` which is not correct because it opens with `<div class='output co'><span class='message'>`. 
This could lead the browser to not auto correct the same on the first line and other lines, hence the difference seen.

````r
> extract_output_part <- function(html) {
+     s <- stringr::str_locate(html, "<div class='output co'>")[, "start"]
+     stringr::str_sub(html, s)
+ }
> 
> html1 <- downlit::evaluate_and_highlight('message("a")')
> extract_output_part(html1)
[1] "<div class='output co'>#&gt; <span class='message'>a</span></div>"
> 
> html2 <- downlit::evaluate_and_highlight('googlesheets4:::gs4_success("a")')
> extract_output_part(html2)
[1] "<div class='output co'>#&gt; <span class='message'><span style='color: #00BB00;'>v</span><span> a</span></div></span>"
````

I can't do a reprex above because this does not happens inside `reprex::reprex()` call - not interactive session ?
``` r
extract_output_part <- function(html) {
  s <- stringr::str_locate(html, "<div class='output co'>")[, "start"]
  stringr::str_sub(html, s)
}

html1 <- downlit::evaluate_and_highlight('message("a")')
extract_output_part(html1)
#> [1] "<div class='output co'>#&gt; <span class='message'>a</span></div>"

html2 <- downlit::evaluate_and_highlight('googlesheets4:::gs4_success("a")')
extract_output_part(html2)
#> [1] "<div class='output co'>#&gt; <span class='message'>v a</span></div>"
```

<sup>Created on 2021-03-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9002)</sup>

Hope it helps.

**Comment by hadley** [comment]
Somewhat more minimal reprex:

``` r
library(downlit)

f <- function() cli::cli_alert_danger("x")
cat(evaluate_and_highlight("f()"))
#> <div class='input'><span class='fu'>f</span><span class='op'>(</span><span class='op'>)</span></div><div class='output co'>#&gt; <span class='message'>x x</span></div>
```

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hadley** [comment]
Even simpler reprex:

``` r
x <- "<div><span class='message'>\033[31mx\033[39m x</span></div>"
fansi::sgr_to_html(x)
#> [1] "<div><span class='message'><span style='color: #BB0000;'>x</span><span> x</span></div></span>"
```

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hadley** [comment]
@jennybc this makes the output consistent, but consistently bold. Removing the bold in https://github.com/r-lib/pkgdown/pull/1644 .
