### ISSUE TITLE
Error with tables

### ISSUE THREAD

**Issue by krlmlr** [r-lib/downlit#80]
``` r
downlit::downlit_md_string("
| Girth | Height | Volume |
|------:|-------:|-------:|
|   8.3 |     70 |   10.3 |
")
#> Error in FUN(X[[i]], ...): is.list(x) is not TRUE
```

<sup>Created on 2021-03-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Maybe related: https://github.com/r-lib/downlit/issues/67.

**Comment by hadley** [comment]
Yeah dup of #67
