### ISSUE TITLE
pkgdown fails if packages used in \dontrun{} are missing

### ISSUE THREAD

**Issue by rhijmans** [r-lib/downlit#85]
pkgdown fails if packages used in \dontrun{} are missing --- perhaps only if not declared in Depends or similar --- even when using `run_dont_run = FALSE`.  An example is `predict.Rd` in the raster package if you do not have `pls` or `randomForest` installed.

**Comment by hadley** [comment]
Yup, looks like a donwlit issue, so I've moved it there.

**Comment by hadley** [comment]
Minimal reprex:

``` r
downlit::autolink_url(vignette(foo, package = "bar"))
#> Error in find.package(package, lib.loc): there is no package called 'bar'
```

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hadley** [comment]
I already fixed this but forgot to add a news bullet: https://github.com/r-lib/downlit/commit/47270f5bfe400ccf1db6b6c16e809cf538c0f021
