### ISSUE TITLE
Ideas to improve the examples in pkgdown

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/downlit#90]
Some of these need support from downlit as well.

![Screen Shot 2021-04-29 at 15 04 22](https://user-images.githubusercontent.com/660288/116556548-db0a2700-a8fd-11eb-91fc-60ec2a550907.png)

* the horizontal lines can be in the manual
* separate input and output by some space
* make it easier to see what is input and what is output
* make it easier to spot the errors

(the greys should be the same greys.... and the bars should be vertical... and ignore the cursor that was caught in the screenshot)

**Comment by hadley** [comment]
Proposed class names: r-in = input, r-out = output, r-msg = message, r-err = error, r-wrn = warning.

And `pr` for prompt?

**Comment by gaborcsardi** [comment]
Yeah. Or `r-pr`?
